### ISSUE TITLE
Release for Scalacheck 1.15

### ISSUE THREAD

**Issue by howyp** [ChocPanda/scalacheck-magnolia#170]
Hey @ChocPanda , any chance there could be a release soon for Scalacheck 1.15.x please? It would be really helpful for us 😀

**Comment by kubukoz** [comment]
Scalacheck 1.15.x is binary compatible with 1.14.x, i think you can just update the dependency in your project for the time being.

**Comment by howyp** [comment]
Ok - makes sense, thanks!
