### ISSUE TITLE
0.3.2 not showing on Maven Central yet?

### ISSUE THREAD

**Issue by howyp** [ChocPanda/scalacheck-magnolia#92]
Hey! thanks for the lib, really helping us at the moment.

I can't see the latest release on maven central at the moment, any idea why it's missing? Or should I be looking somewhere else (I was following the link in the readme)?

https://search.maven.org/search?q=g:com.github.chocpanda%20AND%20a:scalacheck-magnolia_2.12
https://search.maven.org/search?q=g:com.github.chocpanda%20AND%20a:scalacheck-magnolia_2.13

**Comment by ChocPanda** [comment]
That'll be my fault I need to push a tag. I'll do it this evening, I'm glad you're finding this helpful

**Comment by ChocPanda** [comment]
I'm not sure why that version isn't in there I'll take a look at Travis and see if it missed something

**Comment by kubukoz** [comment]
It does appear not to be there:

https://repo1.maven.org/maven2/com/github/chocpanda/scalacheck-magnolia_2.12/
https://repo1.maven.org/maven2/com/github/chocpanda/scalacheck-magnolia_2.13/

**Comment by ChocPanda** [comment]
This was just due to a failed CI build. It should now be available
I am very sorry this took so long. My day job was super hectic for a while
